---

- include_tasks: mail.yml
  when: notify_mail_to != ""
  tags: [notify]

- include_tasks: jabber.yml
  when: notify_jabber_to != ""
  tags: [notify]

- include_tasks: slack.yml
  when: notify_slack_webhook != ""
  tags: [notify]

