---

- name: Send email notify
  mail:
    to="{{notify_mail_to}}"
    host="{{notify_mail_host}}"
    port="{{notify_mail_port}}"
    subject="{{notify_message}}"
    from="{{notify_mail_from}}"
    cc="{{notify_mail_cc}}"
    attach="{{notify_mail_attach}}"
    charset=utf8
  when: notify_mail_to != ""

- name: Send jabber notify
  jabber:
      to="{{notify_jabber_to}}"
      user="{{notify_jabber_user}}"
      password="{{notify_jabber_password}}"
      host="{{notify_jabber_host}}"
      port="{{notify_jabber_port}}"
      msg="{{notify_message}}"
  when: notify_jabber_to != ""
