---

- include: mail.yml
  when: notify_mail_to != ""
  tags: [notify]

- include: jabber.yml
  when: notify_jabber_to != ""
  tags: [notify]

- include: slack.yml
  when: notify_slack_webhook != ""
  tags: [notify]

