---

- name: Get output from shell
  shell: "{{notify_slack_shell}}"
  register: notify_slack_output
  when: notify_slack_shell != ""

- set_fact:
    notify_slack_payload:
      text: "{{notify_message}}\n{{notify_slack_output.stdout|default('')|escape}}" 
      username: "{{notify_slack_username}}"
      icon_emoji: "{{notify_slack_icon}}"
      channel: "{{notify_slack_channel}}"

- name: Send Slack notify
  uri:
    url: "{{notify_slack_webhook}}"
    body_format: json
    body: "{{notify_slack_payload}}"
    method: POST
  when: notify_slack_webhook != ""

